### ISSUE TITLE
Release v1 checklist

### ISSUE THREAD

**Issue by hongaar** [exivity/ui#185]
Issue to keep track of changes in a first stable release.

## Code

- [ ] Get rid of Heading type prop, use `as` instead and style with `h1& {} h2& {}` etc.'
- [ ] Standardize the use of `styled-system` a bit better
- [ ] Rethink about what components we actually need to expose as root components (e.g. SelectInput, SelectList, ListItem, List, ListFocus, SelectList). Better to group components by use case, and export sub-components from those.

---

## Docs

- [ ] Working examples
- [ ] Update logo font
- [ ] Make flat list of components in Storybook (no more atoms/molecules/etc, it's super arbitrary)
- [ ] Standardize Storybook (README.md for each component)

---

## Build

- [ ] Move to GitHub Actions
